pool:
  name: Host

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your Node.js version
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run build
      - name: Build the project
        run: npm run build

      # Step 5: Run tests
      - name: Run tests
        run: npm test

      # Step 6: Validate package-lock.json
      - name: Validate package-lock.json
        run: npm ci --dry-run
