trigger: none

pool:
  name: devasc-anisa

steps:
# Checkout code dari repository GitHub
- task: Checkout@1
  inputs:
    repository: 'self'
    clean: true

# Setup Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Install dependencies
- script: |
    npm audit
  displayName: 'Install Dependencies'

# Linting dengan fix
- script: |
    - script: |
    npx eslint --config client/eslint.config.js client --fix --format json -o eslint-report.json
  displayName: 'Run ESLint with Fix and Report'

# Publish report
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'eslint-report.json'
    ArtifactName: 'ESLint Report'
  displayName: 'Publish ESLint Report'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'FP-PSO-11_FP-PSO-11_AZPKLNXakXt54pvTXdAs'
    cliProjectName: 'Portal Lomba'
    cliSources: '.'

# Task analisis (biasanya ada setelahnya)
- task: SonarQubeAnalyze@7
  displayName: 'Run SonarQube analysis'

# Task publish report ke artifact
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'sonar-report'
    publishLocation: 'Container'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'anisarahmah/react'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'portal-lomba'
    addPipelineData: false
    addBaseImageData: false
