version: "3.9"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80" # Map frontend to localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000" # Map backend to localhost:5000
