apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-api-deployment
spec:
  replicas: 1 # How many copies of your server to run
  selector:
    matchLabels:
      app: portal-api
  template:
    metadata:
      labels:
        app: portal-api
    spec:
      containers:
      - name: api-container
        image: ghcr.io/nerdypengu/portal-lomba-api:latest
        ports:
        - containerPort: 8080